# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import heartbeat_pb2 as heartbeat__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Call = channel.unary_unary(
        '/HbData.Greeter/Call',
        request_serializer=heartbeat__pb2.HbRequest.SerializeToString,
        response_deserializer=heartbeat__pb2.HbReply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Call(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Call': grpc.unary_unary_rpc_method_handler(
          servicer.Call,
          request_deserializer=heartbeat__pb2.HbRequest.FromString,
          response_serializer=heartbeat__pb2.HbReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HbData.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
